### ISSUE TITLE
Segmentation fault on exit (Ubuntu)

### ISSUE THREAD

**Issue by jhonny-oliveira** [vi3itor/GameplayFootball#3]
Hi!

The game throws a Segmentation fault on exit (Ubuntu 21.04), everything else seem to run fine. You can find the log in attachment.
[gameplayfootball-SegFaultLogs.txt](https://github.com/vi3itor/GameplayFootball/files/6797188/gameplayfootball-SegFaultLogs.txt)

I have tried the workaround you mentioned "remove SDL_QuitSubSystem(SDL_INIT_VIDEO); from opengl_renderer3d.cpp", but the result is exactly the same. Any other ideas? Btw, my VM has 6 vCPUs and my computer 8.

Thank you!

**Comment by vi3itor** [comment]
Hi! 

Hard to say without debugging. I will be able to get to my Ubuntu machine after the weekend and I hope to find the cause of the problem.

Thanks!

**Comment by vi3itor** [comment]
Hi Jhonny! 

I've found the cause of the issue and it should be gone now. Please check it out and let me know.

Also, as you suggested [earlier](https://github.com/BazkieBumpercar/GameplayFootball/issues/4#issuecomment-873416891), I removed SQLite3 sources (all of them :smile:) and updated `CMakeLists.txt` to use a system installation. Please create a PR with your patches and I will merge them into upstream. Thanks!

**Comment by jhonny-oliveira** [comment]
Thank you Victor!

Your fix did the job. Only one more clarification and I think I can finally publish the game.

For desktop integration purposes I needed an icon for the game. In the absence of in source alternatives, I took the liberty of using your github user's icon. Is this OK with you? Once this is sorted, I will publish the game.

Concerning the patches I mentioned earlier, I don't think they are "merge request" ready. I built them for the sole purpose of assembling the Ubuntu package. I'm quite sure they can be made smarter to work on every OS.

- 001-CMAKE_set_install_dir.patch - needs proper CMake logic to work for every OS. Probably also needs some code adjustment to support running the binary and data from different locations.
- 002-Config2UserHome.patch - needs code adjustments to work for every OS.
- 003-use_system_sqlite3.patch - just for the record, I think your solution was much better.

[001-CMAKE_set_install_dir.txt](https://github.com/vi3itor/GameplayFootball/files/6854573/001-CMAKE_set_install_dir.txt)
[002-Config2UserHome.txt](https://github.com/vi3itor/GameplayFootball/files/6854575/002-Config2UserHome.txt)
[003-use_system_sqlite3.txt](https://github.com/vi3itor/GameplayFootball/files/6854576/003-use_system_sqlite3.txt)

Cheers!

**Comment by vi3itor** [comment]
Hi Jhonny! 

> For desktop integration purposes I needed an icon for the game. In the absence of in source alternatives, I took the liberty of using your github user's icon. Is this OK with you? Once this is sorted, I will publish the game.

It's totally fine with me, the image is license-free.

As for the patches, I'll try to integrate them into master once I'm ready to finalize and merge changes from windows branch. But it will take me some time, so you should probably publish the game with patches for now.  

Thank you!

**Comment by jhonny-oliveira** [comment]
Great! Thank you!

The game is published. It  can be installed by 
- adding the XtraDeb play PPA: https://launchpad.net/~xtradeb/+archive/ubuntu/play
Or
- installing one of the XtraDeb matching repo packages: https://launchpad.net/~xtradeb/+archive/ubuntu/apps/+sourcepub/12266410/+listing-archive-extra

and then:

`sudo apt update && sudo apt install gameplayfootball`

I think this one can be closed.
Btw, tagging and making a release would be really helpful for future new versions detection.

Cheers!
Jhonny@XtraDebb

**Comment by vi3itor** [comment]
Thank you Jhonny! I will add your instructions to the README for those who'd like to install and play the game on Ubuntu. As soon as I merge `windows` branch, I'll start tagging release versions.
