### ISSUE TITLE
Missing release 0.2

### ISSUE THREAD

**Issue by jhonny-oliveira** [vi3itor/GameplayFootball#9]
Hi Victor!

Something happened to the release/tag 0.2 and now my package (version) watch file fails. Could you please re-create it or maybe create 0.3?

I noticed this also happened in a couple of other GitHub repos at the same time, not sure why though! GitHub maintenance?!?

Thank you!
Jhonny Oliveira
https://xtradeb.net

**Comment by vi3itor** [comment]
Hi Jhonny! I don't know what happened, but I have recreated a release tag `0.2`. Please check it out and let me know!

**Comment by jhonny-oliveira** [comment]
Looks good!

Thanks!
